// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC7oc2Db6KH_RR4hNqWdLAKtINQvrZicLw',
    appId: '1:499217642338:web:fd6bb2bdfd4ea0d803323b',
    messagingSenderId: '499217642338',
    projectId: 'gamepigeonleague',
    authDomain: 'gamepigeonleague.firebaseapp.com',
    storageBucket: 'gamepigeonleague.firebasestorage.app',
    measurementId: 'G-T84XX92F1W',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCb8t3N43qX1CDyRKxe_fy1o1buBYxO168',
    appId: '1:499217642338:android:a0485cad37dc01ba03323b',
    messagingSenderId: '499217642338',
    projectId: 'gamepigeonleague',
    storageBucket: 'gamepigeonleague.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBOPUGQnF11-mU8Luf-k3IgiSXIPYNY09A',
    appId: '1:499217642338:ios:37f0b1c853907c8303323b',
    messagingSenderId: '499217642338',
    projectId: 'gamepigeonleague',
    storageBucket: 'gamepigeonleague.firebasestorage.app',
    iosBundleId: 'com.example.frontend',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBOPUGQnF11-mU8Luf-k3IgiSXIPYNY09A',
    appId: '1:499217642338:ios:37f0b1c853907c8303323b',
    messagingSenderId: '499217642338',
    projectId: 'gamepigeonleague',
    storageBucket: 'gamepigeonleague.firebasestorage.app',
    iosBundleId: 'com.example.frontend',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC7oc2Db6KH_RR4hNqWdLAKtINQvrZicLw',
    appId: '1:499217642338:web:11c645b9b5b88e2003323b',
    messagingSenderId: '499217642338',
    projectId: 'gamepigeonleague',
    authDomain: 'gamepigeonleague.firebaseapp.com',
    storageBucket: 'gamepigeonleague.firebasestorage.app',
    measurementId: 'G-1HNL9YBEVD',
  );
}
